version: 0.2
env:
  variables:
    S3_ENVIRONMENT_BUCKET: "period-app-frontend"
    Project: "frontend"
    Service: "service"
    ENVIRONMENT_FILE: "period-app"
phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - npm install
  build:
    commands:
      - aws s3 cp s3://${S3_ENVIRONMENT_BUCKET}/${Project}/${Service}/${ENVIRONMENT_FILE} .env
      - echo Build Phase
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-path: no
  base-directory: build
#   post_build:
#     commands:
#       - echo PostBuild Phase
#       - aws s3 sync ./dist s3://recruitment.enum.africa
#       - aws cloudfront create-invalidation --distribution-id E713H8OBS9MWP --paths "/*";
